### ISSUE TITLE
New release of pass-extension-tail

### ISSUE THREAD

**Issue by szlin** [palortoff/pass-extension-tail#1]
Would you mind releasing the version of pass-extension-tail?

- https://github.com/palortoff/pass-extension-tail/releases

I can package this awesome tool into Debian archive afterwards.

Thank you!

**Comment by palortoff** [comment]
Done. [1.0.0](https://github.com/palortoff/pass-extension-tail/releases/tag/v1.0.0) just released.

Will you take care of the install script? I don't have any experience in that...
Are you planning to add it to a package repository?

**Comment by szlin** [comment]
We will handle it.
