### ISSUE TITLE
Abstraction, semantic of sub-commands

### ISSUE THREAD

**Issue by christian-weiss** [palortoff/pass-extension-tail#10]
While "pass" is trying to abstract all commands from underlying encryption statements to give the user a streamlined experience when dealing with passwords, this way the user do not need to take care underlying statements, a point where this plugin fails (i love this plugin for its features). 

This plugin should follow the same semantic as the main program. As "tail" is a technical aspect, the plugin should the emphasis on "what to do" not on "how to do", as the main program does. 

Suggested sub-command name (instead of "tail"):
- showmeta
instead of "tailedit":
- editmeta

The old sub-commands should be deprecated but still existing for a grace period.
I know this feels like a "big change" because "tail" is part of the plugin name, but please do the change.

**Comment by palortoff** [comment]
Built-in pass commands are not all abstract. At least grep and git are highly technical.

Tail may be a technical term I suppose everyone using a password manager with a command line interface is very familiar with it.

Neither the plugin itself nor the commands will be renamed. I do not consider the naming failed...
