### ISSUE TITLE
Hide OTP from Tail

### ISSUE THREAD

**Issue by 1337god** [palortoff/pass-extension-tail#12]
From https://github.com/tadfisher/pass-otp

**Comment by palortoff** [comment]
This extension - just as pass itself - does not assume any structure of data beyond the first line. Therefore any data after line 1 should not be hidden.

On a side note I think storing OTP seed along with passwords is an inherently bad idea. OTP are usually used as a second factor. Storing both factors together beats the purpose of two factor authentication.
