### ISSUE TITLE
Feature Request: Show password, but red on red to make it copy-and-paste-able, but still not visible

### ISSUE THREAD

**Issue by xtaran** [palortoff/pass-extension-tail#15]
Since I occasionally use `pass` via SSH, automatically copying passwords into the clipboard is not always doable.

I used Keepass and especially `kpcli` before. With `kpcli` I really liked its way to output datasets with the password itself in red text on red background. That way, the password is not visible to any bystander, but I can easily copy and paste it with the mouse or with GNU Screen into a copy-and-paste buffer. The color also shows me where the boundaries of the password are.

I might implement this myself, but if I do so, I'll likely base it on the code of pass-extension-tail. So I wondered if such a feature would be in the scope of pass-extension-tail itself, maybe as `pass color` or `pass ctail`. Or with an option, maybe  `-c`.

**Comment by willpower232** [comment]
I like the idea of this but the whole point of `pass tail` is to see the contents without the password so a separate extension for pass would probably make more sense.

**Comment by palortoff** [comment]
I think a separate extension would make more sense. Let's keep it the unix way - do one thing and do it right.

Of course you are welcome to reuse the code. I heavily borrowed from the original `pass` implementation myself.

**Comment by willpower232** [comment]
Do holler if you get round to making the extension!
