### ISSUE TITLE
Add CHANGELOG file

### ISSUE THREAD

**Issue by szlin** [palortoff/pass-extension-tail#2]
Could you create CHANGELOG file and update this in each release?

You may refer to [1].

Thank you.

ref:
[1]:https://github.com/jarun/googler/blob/master/CHANGELOG

**Comment by palortoff** [comment]
Changelog added.
I also made a new release, containing the man page.

Thank you for adding the tool to the debian package archive!

**Comment by szlin** [comment]
Thanks for your effort.

Gavin and I are working together in order to put this tool into Debian archive :)
