### ISSUE TITLE
Copy first line to clipboard and print tail at same time?

### ISSUE THREAD

**Issue by benlindsay** [palortoff/pass-extension-tail#6]
This is a great extension, thanks for making it!

I'm not sure how hard this would be, or if there's already a way of doing it, but I would really like to be able to copy the password to clipboard and print all lines except for the password to terminal to remind me my username and such. I'm imagining something like this:

    $ pass tail -c amazon.com
    URL: *.amazon.com/*
    Username: AmazonianChicken@example.com
    Copied amazon.com to clipboard. Will clear in 45 seconds.

What would be the best way of achieving something like this?

**Comment by palortoff** [comment]
That's a great idea. It is absolutely worth adding to this project.

It should not be that hard, but I do not have the time right now. You are more than welcome to send a pull request.

As a workaround for now you could define a function in `.bashrc` like this (not tested, written from the top of my head)

```
pass_tc() {
  pass tail $1
  pass -c $1
}
```

**Comment by benlindsay** [comment]
Thanks! I put a function like that in my `.bashrc` but I'm not familiar
enough with custom tab completion to get that working for a custom function
like that. If you have any quick tips on ways to set that up I'd appreciate
that.

I don't think I have the time to put in a pull request right now either,
but maybe some day.

Thanks!

**Comment by benlindsay** [comment]
Ok I figured it out. Here's my full hacky way to implement this including tab completion:

1. Add the following to my `.bashrc`:

```
function passtail() {
  pass -c $1
  pass tail $1
}
if [ -f /usr/local/etc/bash_completion.d/passtail ]; then
  source /usr/local/etc/bash_completion.d/passtail
fi
```
Where the `passtail` bash completion file sits in the same place as the `pass` bash completion file`

2. Copy the `pass` bash completion file into a `passtail` bash completion file:

```
cp /usr/local/etc/bash_completion.d/pass /usr/local/etc/bash_completion.d/passtail
```

3. Go to line 84 in the `passtail` file and remove all subcommands, so

```
local commands="init ls find grep show insert generate edit rm mv cp git help version tail tailedit"
```
becomes
```
local commands=""
```

4. Go to the final line in the `passtail` file and change
```
complete -o filenames -F _pass pass
```
to
```
complete -o filenames -F _pass passtail
```

I'm sure there are more elegant ways to do this, but this is working for me.

**Comment by benlindsay** [comment]
Unfortunately now that I'm trying out zsh, the above hack doesn't seem to work, even when I do stuff like

```
autoload bashcompinit
bashcompinit
source /path/to/your/bash_completion_file
```

as mentioned [here](https://stackoverflow.com/a/8492043/2680824).  Any advice would be welcome :/
