### ISSUE TITLE
default pass action

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [palortoff/pass-extension-tail#9]
Is it possible replace the default action for pass
So ```% pass somepass``` would do the same as ```% pass tail somepass```?

**Comment by palortoff** [comment]
No. that is not possible.
Some time last year there was a discussion on the password-store mailing list if it should be allowed to override the default action, but the idea was dismissed.

The easiest workaround would be to define an alias in `.bashrc`:
`alias pt='pass tail '`

**Comment by c-e-p-x-u-o** [comment]
Thank you!
